cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('remove/', views.cart_remove, name='cart_remove'),
    path('update/', views.cart_update, name='cart_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('', include('store.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.CartView, name='cart'),
    path('orderplaced/', views.order_placed, name="order_placed"),
   # path('error/', views.Error.as_view(), name="error"),
   # path('webhook/', views.stripe_webhook)
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from store.models import Product
from .cart import Cart 

def cart_summary(request):
    return render(request, 'cart/summary.html')

def cart_add(request):
    cart = Cart(request)
    
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)
        return JsonResponse({'qty': cart.__len__()})

def cart_remove(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        cart.remove(product_id=(int(request.POST.get('productid'))))
        return JsonResponse({'qty': cart.__len__(), 'subtotal': (cart.get_subtotal_price())})

def cart_update(request):
    cart = Cart(request)
    
    if request.POST.get('action') == 'post':
        productid = int(request.POST.get('productid'))
        productqty = int(request.POST.get('productqty'))
        price = cart.update(product_id=productid, qty=productqty)
        return JsonResponse({'qty': cart.__len__(), 'totalprice': price, 'subtotal': (cart.get_subtotal_price())})
    

templates/cart/summary.html
{% extends '../store/base.html' %}
{% load static %}
{% block title %}Shopping Cart{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container" style="max-width: 1000px">
    <div class="col-12">
      <h1 class="h2">Your Shopping Cart</h1>
    </div>
    <div class="col-12">
      <p>Manage your <b>books</b> in your shopping cart</p>
    </div>
    <hr />
  </div>
  <div class="container" style="max-width: 1000px">
    
    <div class="row g-3">
      <div class="col-12 bg-light p-3 d-flex justify-content-between">
        <div class="d-flex d-flex-inline">
          <div class="pe-3">Order</div>
          <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
          Shipping options
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
          </svg>
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">Next day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul>
          </div>
        </div>
        <div class="text-end">
          
          <div class="">Sub Total: <span class="fw-bold">$</span><div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div></div>
          <div id="">Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">$11.50</span></div>
          <div class="pt-2">Total to pay: <span class="fw-bold h5">$</span><span id="total" class="fw-bold h5">{{cart.get_total_price}}</span></div>
          
        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
        <div class="d-grid gap-2 ">
          <a role="button" href="{% url "payment:cart" %}" class="btn btn-success fw-bold" type="button">Checkout</a>
          <button class="btn btn-light" type="button">Save for later</button>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 p-0">

        {% for item in cart %} 
        {% with product=item.product %}

        <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid mx-auto d-block" alt="Responsive image"
                  src="{{ product.image.url }}" />
            </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                  <p class="card-text pb-3">{{product.title}}</p>
                </a>
                    <label for="select">Qty</label>
                    <select id="qty-select" data-index="{{product.id}}" style="width:50px;height:31px;">
                      <option value="" selected disabled hidden>{{item.qty}}</option>
                      <option value="">1</option>
                      <option value="">2</option>
                      <option value="">3</option>
                      <option value="">4</option>
                    </select>
                <a type="button" id="remove-button" data-index="{{product.id}}" class="delete-button text-decoration-none small">Remove</a>
              </div>
            </div>
          </div>
        </div>
        {% endwith %} 
        {% endfor %}
      </div>
    </div>
    
  </div>
</main>

  <script>

    $(document).on('change', '#qty-select', function (e) {
      e.preventDefault();
      product_id = $(this).attr('data-index');
      $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_update" %}',
        data: {
            productid: product_id,
            productqty: $(this).find(':selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
        },
        success: function (res) {
          document.getElementById("cart-qty").innerHTML = res.qty;
          document.getElementById("subtotal").innerHTML = res.subtotal;
          $('.total-price[data-index="' + product_id + '"]').empty();
          $('.total-price[data-index="' + product_id + '"]').html('$' + res.totalprice);
        },
        error: function (xhr, errmsg, err) {}
    });
    });

    $(document).on('click', '#remove-button', function (e) {
      e.preventDefault();
      product_id = $(this).attr('data-index');
      console.log(product_id);
      $.ajax({
          type: 'POST',
          url: '{% url "cart:cart_remove" %}',
          data: {
              productid: product_id,
              csrfmiddlewaretoken: "{{csrf_token}}",
              action: 'post'
          },
          success: function (res) {
            $('.product-item[data-index="' + product_id + '"]').remove();
            document.getElementById("cart-qty").innerHTML = res.qty
            document.getElementById("subtotal").innerHTML = res.subtotal;
          },
          error: function (xhr, errmsg, err) {}
      });
    });
  </script>
{% endblock %}